version: '3.9'

x-postgres-variables: &postgres-variables
  POSTGRES_DB: "${DB_NAME}"
  POSTGRES_USER: "${DB_USER}"
  POSTGRES_PASSWORD: "${DB_PASSWORD}"

x-minio-variables: &minio-variables
  MINIO_SERVER_URL: "${MINIO_SERVER_URL}"
  MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
  MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
  MINIO_END_POINT: "${MINIO_END_POINT}"
  MINIO_PORT: "${MINIO_PORT}"
  MINIO_BUCKET: "${MINIO_BUCKET}"


services:
  postgres:
    container_name: postgres-dev-partsorder
    image: postgres:15.2
    restart: always
    environment:
      <<: *postgres-variables
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - './infrastructure/postgres/data:/var/lib/postgresql/data'
    healthcheck:
      interval: 10s
      retries: 10
      test: "pg_isready -U ${DB_USER} -d ${DB_NAME}"
      timeout: 2s

  redis:
    container_name: redis-dev-partsorder
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
