entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: "${SITE}"
          - sans: "*.${SITE}"
# http:
#  routers:
#    http-catchall:
#      rule: hostregexp(`{host:.+}`)
#      entrypoints:
#        - http
#      middlewares:
#        - redirect-to-https
#  middlewares:
#    redirect-to-https:
#      redirectScheme:
#        scheme: https
#        permanent: false

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /custom
    watch: true

api:
  dashboard: true

certificatesResolvers:
  letsencrypt:
    acme:
      dnsChallenge:
        delayBeforeCheck: "15"
        provider: cloudflare
        resolvers:
          - 1.1.1.1:53
          - 1.0.0.1:53
      email: info@${SITE}
      storage: /letsencrypt/acme.json
