name: Pull request
on:
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  eslint-client:
    name: EsLint client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 19.8.1
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm i
      - name: EsLint
        run: npm run lint

  test-client:
    name: Test client
    runs-on: ubuntu-latest
    needs: eslint-client
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 19.8.1
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm i

  eslint-server:
    name: EsLint server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 19.8.1
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm i
      - name: EsLint
        run: npm run lint

  test-server:
    name: Test Server
    runs-on: ubuntu-latest
    needs: eslint-server
    defaults:
      run:
        working-directory: server
    env:
      SECRET_KEY: 'secret_key'
      DATABASE_URL: 'postgresql://postgres:1234@postgres:1234/partsorder'
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345678
      MINIO_END_POINT: minio
      MINIO_PORT: 9000
      MINIO_BUCKET: storage
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 19.8.1
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm i
      - name: Generate types
        run: npm run generate
      - name: Test
        run: npm run test
