name: Release

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  eslint-client:
    name: EsLint client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 19.8.1
      - uses: actions/checkout@v3
      - name: Install dependency
        run: npm i -g pnpm
      - name: Install dependency
        run: pnpm i
      - name: EsLint
        run: pnpm run lint

  test-client:
    name: Test client
    runs-on: ubuntu-latest
    needs: eslint-client
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 19.8.1
      - uses: actions/checkout@v3
      - name: Install dependency
        run: npm i -g pnpm
      - name: Install dependency
        run: pnpm i

  build-client:
    name: Build client
    runs-on: ubuntu-latest
    needs: test-client
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extra metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/partsorder-client
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./client
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  eslint-server:
    name: EsLint server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 19.8.1
      - uses: actions/checkout@v3
      - name: Install dependency
        run: npm i
      - name: EsLint
        run: npm run lint

  test-server:
    name: Test Server
    runs-on: ubuntu-latest
    needs: eslint-server
    defaults:
      run:
        working-directory: server
    env:
      SECRET_KEY: 'secret_key'
      DATABASE_URL: 'postgresql://postgres:1234@postgres:1234/partsorder'
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345678
      MINIO_END_POINT: minio
      MINIO_PORT: 9000
      MINIO_BUCKET: storage
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 19.8.1
      - uses: actions/checkout@v3
      - name: Install dependency
        run: npm i
      - name: Generate types
        run: npm run generate
      - name: Test
        run: npm run test

  build-server:
    name: Build server
    runs-on: ubuntu-latest
    needs: test-server
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extra metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/partsorder-server
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./server
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    needs: [build-client, build-server]
    steps:
      - name: Settings ssh
        run: |
          apt-get install openssh-client
          eval $(ssh-agent -s)
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo -e "$DEPLOY_KEY_PRIVATE" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          echo "$DEPLOY_KEY_PRIVATE" | tr -d '\r' | ssh-add -
      - name: Deploy application
        run: |
          ssh -o StrictHostKeyChecking=no "$DEPLOY_USER@$DEPLOY_HOST" ""$DEPLOY_COMMAND""
